// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgbrtfetdsqhkyxbyfkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnYnJ0ZmV0ZHNxaGt5eGJ5ZmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTg4NjMsImV4cCI6MjA2NTU3NDg2M30.sUdtZb03J-LflK1_mBGtJK9v9K02_w-CsKg5yBTZELQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);